# Generated by Django 4.1.4 on 2022-12-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='mainText',
            new_name='main_text',
        ),
    ]
